version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    container_name: 'tutorial_nginx'
    depends_on:
        - app
  app:
      build:
          context: .
          dockerfile: ./docker/app/Dockerfile
      volumes:
          - ./:/var/www
      container_name: project_app

