version: '3'
services:
    nginx:
        image: 'nginx:latest'
        volumes:
            - './:/var/www/'
            - './docker/nginx/conf.d/:/etc/nginx/conf.d/'
        ports:
            - '80:80'
        container_name: tutorial_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
            args:
                USER_ID: '${USER_ID}'
                GROUP_ID: '${GROUP_ID}'
        volumes:
            - './:/var/www'
        container_name: project_app
        depends_on:
            - db
    db:
        image: 'mysql:8.0.1'
        restart: always
        volumes:
            - 'dbdata:/var/lib/mysql'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        command: --default-authentication-plugin=mysql_native_password
        container_name: project_db
volumes:
    dbdata:
